# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15PFhJ6eiusDFKyQa0CcbRzsqK-l2WXqg
"""

with open("twitter_download/2016train.tsv") as tweets_train_file:
    train_file_lines = tweets_train_file.readlines()
    
with open("twitter_download/2016test.tsv") as tweets_test_file:
    test_file_lines = tweets_test_file.readlines()

f1 = open("2016train_processed.tsv", "a")
f2 = open("2016test_processed.tsv", "a")

def process_file_and_save(lines, save_to):
    for line in lines:
        items = line.split("\t")
        if "Not Available" in items[2]:
            continue
        
        tokens = items[2].rstrip().split()
        result = []
        for token in tokens:
            if "@" in token:
                #remove all the @
                token  = token.replace("@", "")
                result.append(token)
            elif "http" in token:
                #remove all the links
                token = ""
                result.append(token)
            elif "#" in token:
                token = token.replace("#", "")
                result.append(token)
            else:
                result.append(token)
        processed_str = " ".join(result)
        final_line = items[0] + '\t' + items[1] + '\t' + processed_str + '\n'
        save_to.write(final_line)

process_file_and_save(train_file_lines, f1)
process_file_and_save(test_file_lines, f2)

f1.close()
f2.close()

